import imgLabTech from "@/imports/IteriDsComponentes/4c8ff3ca561a24d7b6879ee43a3e3b4eb45abafc.png";
import imgAiResearch from "@/imports/IteriDsComponentes/dd45cd512440e55db1f5ae98081416dfae888ba9.png";
import imgEventsStaff from "@/imports/IteriDsComponentes/450d9f0db4d4357b23323afe55ec5841dc0b14fd.png";
import imgLabCoats from "@/imports/IteriDsComponentes/f451825a67aaf0e6ed41ffc1b4e4713b3f45119e.png";

import avatarWoman1 from "@/imports/IteriDsComponentes/64e9a10bc90e68f4322d633195c6975add5fe632.png";
import avatarMan1 from "@/imports/IteriDsComponentes/6fd3270ad94724c5b0c2016c4fe7dbad6d1dcf62.png";
import avatarWoman2 from "@/imports/IteriDsComponentes/7248301207b3e0180c17e84a4e05538659595478.png";
import avatarWoman3 from "@/imports/IteriDsComponentes/7263cbf8a9745f1e1da4e19f85eee448eee7a57d.png";
import avatarMan2 from "@/imports/IteriDsComponentes/907a440bf78bfc9400fb0367ab52dac5eb2d1e28.png";
import avatarWoman4 from "@/imports/IteriDsComponentes/f7642c3c3358a483aa606ae6f52f04d13d6f1ca0.png";

import type {
  Application,
  Notification,
  OffererProfile,
  Opportunity,
  StudentProfile,
  User,
} from "./types";

export const AVATARS = {
  woman1: avatarWoman1,
  man1: avatarMan1,
  woman2: avatarWoman2,
  woman3: avatarWoman3,
  man2: avatarMan2,
  woman4: avatarWoman4,
};

export const CATEGORY_IMAGES: Record<string, string> = {
  Monitoria: imgLabTech,
  "Iniciação Científica": imgAiResearch,
  Eventos: imgEventsStaff,
  Laboratórios: imgLabCoats,
};

export const SEED_OFFERER_ID = "seed-offerer-1";

export const opportunities: Opportunity[] = [
  {
    id: "opp-1",
    title: "Monitoria de Cálculo I",
    category: "Monitoria",
    knowledgeArea: "Ciências Exatas",
    image: imgLabTech,
    description:
      "Auxiliar o professor titular em aulas de exercícios, plantões de dúvidas e correção de listas para a disciplina de Cálculo I. Ótima oportunidade para reforçar conhecimentos e desenvolver didática.",
    workload: "12h semanais",
    payRate: 25,
    payType: "hour",
    startDate: "2026-08-10",
    applicationDeadline: "2026-08-01",
    requiredSkills: [
      { skill: "Estatística", mandatory: true },
      { skill: "Docência", mandatory: false },
    ],
    minCR: 7,
    requiredCourse: "Engenharia ou Matemática",
    requiredSemester: "3º semestre ou superior",
    status: "active",
    isNew: true,
    isUrgent: false,
    offererId: SEED_OFFERER_ID,
    offererName: "Profa. Ana Beatriz",
    university: "UNICAMP",
    createdAt: "2026-07-01",
  },
  {
    id: "opp-2",
    title: "Iniciação Científica em IA Aplicada",
    category: "Iniciação Científica",
    knowledgeArea: "Ciências Exatas",
    image: imgAiResearch,
    description:
      "Participar de projeto de pesquisa em aprendizado de máquina aplicado a diagnóstico médico, com publicação de artigo ao final do ciclo.",
    workload: "20h semanais",
    payRate: 35,
    payType: "hour",
    startDate: "2026-08-15",
    applicationDeadline: "2026-08-05",
    requiredSkills: [
      { skill: "Python", mandatory: true },
      { skill: "Estatística", mandatory: true },
    ],
    minCR: 8,
    requiredCourse: "Ciência da Computação",
    requiredSemester: "5º semestre ou superior",
    status: "active",
    isNew: false,
    isUrgent: true,
    offererId: SEED_OFFERER_ID,
    offererName: "Prof. Ricardo Nunes",
    university: "USP",
    createdAt: "2026-06-20",
  },
  {
    id: "opp-3",
    title: "Staff de Apoio — Semana de Engenharia",
    category: "Eventos",
    knowledgeArea: "Ciências Humanas",
    image: imgEventsStaff,
    description:
      "Apoio logístico e de recepção durante a Semana de Engenharia: credenciamento, orientação de visitantes e suporte às palestras.",
    workload: "8h (evento de 3 dias)",
    payRate: 20,
    payType: "hour",
    startDate: "2026-09-01",
    applicationDeadline: "2026-08-20",
    requiredSkills: [{ skill: "Atendimento ao Público", mandatory: true }],
    status: "active",
    isNew: true,
    isUrgent: false,
    offererId: SEED_OFFERER_ID,
    offererName: "Coord. Fernanda Lima",
    university: "UFMG",
    createdAt: "2026-07-10",
  },
  {
    id: "opp-4",
    title: "Assistente de Laboratório de Materiais",
    category: "Laboratórios",
    knowledgeArea: "Ciências Exatas",
    image: imgLabCoats,
    description:
      "Apoio na organização, preparo de amostras e manutenção de equipamentos do Laboratório de Ciência dos Materiais.",
    workload: "16h semanais",
    payRate: 28,
    payType: "hour",
    startDate: "2026-08-12",
    applicationDeadline: "2026-08-03",
    requiredSkills: [
      { skill: "Excel", mandatory: true },
      { skill: "Gestão de Projetos", mandatory: false },
    ],
    minCR: 7.5,
    requiredCourse: "Engenharia de Materiais",
    requiredSemester: "4º semestre ou superior",
    status: "active",
    isNew: false,
    isUrgent: false,
    offererId: SEED_OFFERER_ID,
    offererName: "Prof. Diego Martins",
    university: "UFRGS",
    createdAt: "2026-06-28",
  },
  {
    id: "opp-5",
    title: "Monitoria de Algoritmos e Estruturas de Dados",
    category: "Monitoria",
    knowledgeArea: "Ciências Exatas",
    image: imgLabTech,
    description:
      "Conduzir plantões semanais de dúvidas, revisar listas de exercícios e apoiar alunos com dificuldades em lógica de programação.",
    workload: "10h semanais",
    payRate: 26,
    payType: "hour",
    startDate: "2026-08-10",
    applicationDeadline: "2026-07-28",
    requiredSkills: [
      { skill: "React", mandatory: false },
      { skill: "SQL", mandatory: true },
    ],
    minCR: 7,
    status: "active",
    isNew: false,
    isUrgent: true,
    offererId: SEED_OFFERER_ID,
    offererName: "Prof. Marcelo Souza",
    university: "UNICAMP",
    createdAt: "2026-06-15",
  },
  {
    id: "opp-6",
    title: "IC em Redação Científica e Divulgação",
    category: "Iniciação Científica",
    knowledgeArea: "Ciências Humanas",
    image: imgAiResearch,
    description:
      "Apoiar a produção de artigos e materiais de divulgação científica do laboratório, incluindo revisão de textos e redes sociais.",
    workload: "15h semanais",
    payRate: 22,
    payType: "hour",
    startDate: "2026-08-20",
    applicationDeadline: "2026-08-08",
    requiredSkills: [
      { skill: "Redação Científica", mandatory: true },
      { skill: "Design Gráfico", mandatory: false },
    ],
    minCR: 6.5,
    status: "closed",
    isNew: false,
    isUrgent: false,
    offererId: SEED_OFFERER_ID,
    offererName: "Profa. Camila Rocha",
    university: "PUC-Rio",
    createdAt: "2026-05-30",
  },
  {
    id: "opp-7",
    title: "Suporte Técnico — Laboratório de Redes",
    category: "Laboratórios",
    knowledgeArea: "Ciências Exatas",
    image: imgLabCoats,
    description:
      "Vaga preenchida — mantida como referência de histórico de oportunidades do departamento.",
    workload: "12h semanais",
    payRate: 24,
    payType: "hour",
    startDate: "2026-07-01",
    applicationDeadline: "2026-06-20",
    requiredSkills: [
      { skill: "SQL", mandatory: true },
      { skill: "Inglês Técnico", mandatory: false },
    ],
    status: "closed",
    isNew: false,
    isUrgent: false,
    offererId: SEED_OFFERER_ID,
    offererName: "Prof. Diego Martins",
    university: "UFRGS",
    createdAt: "2026-05-10",
  },
  {
    id: "opp-8",
    title: "Monitoria de Anatomia Humana",
    category: "Monitoria",
    knowledgeArea: "Biológicas & Saúde",
    image: imgLabCoats,
    description:
      "Apoiar aulas práticas de anatomia, organização de peças de estudo e plantões de dúvidas para calouros de Medicina.",
    workload: "10h semanais",
    payRate: 24,
    payType: "hour",
    startDate: "2026-08-18",
    applicationDeadline: "2026-08-06",
    requiredSkills: [{ skill: "Docência", mandatory: true }],
    minCR: 7,
    status: "active",
    isNew: true,
    isUrgent: false,
    offererId: SEED_OFFERER_ID,
    offererName: "Profa. Helena Duarte",
    university: "USP",
    createdAt: "2026-07-05",
  },
  {
    id: "opp-9",
    title: "IC em Sistemas Embarcados",
    category: "Iniciação Científica",
    knowledgeArea: "Ciências Exatas",
    image: imgAiResearch,
    description:
      "Desenvolver protótipos com sensores IoT aplicados a monitoramento ambiental no laboratório de eletrônica.",
    workload: "18h semanais",
    payRate: 32,
    payType: "hour",
    startDate: "2026-08-22",
    applicationDeadline: "2026-08-10",
    requiredSkills: [
      { skill: "Python", mandatory: true },
      { skill: "SQL", mandatory: false },
    ],
    minCR: 7.5,
    status: "active",
    isNew: false,
    isUrgent: true,
    offererId: SEED_OFFERER_ID,
    offererName: "Prof. Marcelo Souza",
    university: "UNICAMP",
    createdAt: "2026-07-12",
  },
  {
    id: "opp-10",
    title: "Apoio em Biblioteca e Acervo",
    category: "Eventos",
    knowledgeArea: "Ciências Humanas",
    image: imgEventsStaff,
    description:
      "Organizar acervo de periódicos, apoiar atendimento ao público e catalogação digital na biblioteca central.",
    workload: "12h semanais",
    payRate: 18,
    payType: "hour",
    startDate: "2026-08-14",
    applicationDeadline: "2026-08-02",
    requiredSkills: [
      { skill: "Atendimento ao Público", mandatory: true },
      { skill: "Excel", mandatory: false },
    ],
    status: "active",
    isNew: true,
    isUrgent: false,
    offererId: SEED_OFFERER_ID,
    offererName: "Coord. Fernanda Lima",
    university: "UFMG",
    createdAt: "2026-07-08",
  },
  {
    id: "opp-11",
    title: "Monitoria de Bioquímica",
    category: "Monitoria",
    knowledgeArea: "Biológicas & Saúde",
    image: imgLabCoats,
    description:
      "Auxiliar alunos de Biomedicina em aulas práticas de laboratório e correção de relatórios experimentais.",
    workload: "10h semanais",
    payRate: 25,
    payType: "hour",
    startDate: "2026-08-16",
    applicationDeadline: "2026-08-04",
    requiredSkills: [
      { skill: "Docência", mandatory: true },
      { skill: "Estatística", mandatory: false },
    ],
    minCR: 7,
    status: "active",
    isNew: false,
    isUrgent: false,
    offererId: SEED_OFFERER_ID,
    offererName: "Profa. Helena Duarte",
    university: "USP",
    createdAt: "2026-06-25",
  },
  {
    id: "opp-12",
    title: "Assistente de Laboratório de Química",
    category: "Laboratórios",
    knowledgeArea: "Biológicas & Saúde",
    image: imgLabCoats,
    description:
      "Apoiar preparo de reagentes, organização de vidrarias e manutenção preventiva de equipamentos do laboratório.",
    workload: "14h semanais",
    payRate: 27,
    payType: "hour",
    startDate: "2026-08-20",
    applicationDeadline: "2026-08-09",
    requiredSkills: [{ skill: "Gestão de Projetos", mandatory: false }],
    minCR: 7,
    status: "active",
    isNew: false,
    isUrgent: false,
    offererId: SEED_OFFERER_ID,
    offererName: "Prof. Diego Martins",
    university: "UFRGS",
    createdAt: "2026-06-18",
  },
  {
    id: "opp-13",
    title: "IC em História Econômica Regional",
    category: "Iniciação Científica",
    knowledgeArea: "Ciências Humanas",
    image: imgEventsStaff,
    description:
      "Levantamento e análise de fontes históricas para pesquisa sobre desenvolvimento econômico regional.",
    workload: "12h semanais",
    payRate: 20,
    payType: "hour",
    startDate: "2026-08-25",
    applicationDeadline: "2026-08-12",
    requiredSkills: [{ skill: "Redação Científica", mandatory: true }],
    minCR: 6.5,
    status: "active",
    isNew: false,
    isUrgent: false,
    offererId: SEED_OFFERER_ID,
    offererName: "Profa. Camila Rocha",
    university: "PUC-Rio",
    createdAt: "2026-06-10",
  },
];

export const applications: Application[] = [];

export const notifications: Notification[] = [];

export const users: User[] = [
  {
    id: SEED_OFFERER_ID,
    email: "seed.offerer@unicamp.br",
    role: "offerer",
    name: "Profa. Ana Beatriz",
    avatar: AVATARS.woman2,
    onboardingCompleted: true,
  },
];

export const studentProfiles: StudentProfile[] = [];
export const offererProfiles: OffererProfile[] = [
  {
    userId: SEED_OFFERER_ID,
    roleTitle: "Professor",
    university: "UNICAMP",
    department: "Instituto de Computação",
    siape: "0000000",
    unitName: "Instituto de Computação",
    unitDescription: "Departamento de Ciência da Computação",
    contactEmail: "seed.offerer@unicamp.br",
    contactPhone: "(19) 3000-0000",
    areaOfExpertise: "Inteligência Artificial",
  },
];

export function isOpportunityFilled(opportunityId: string): boolean {
  return applications.some(
    (a) => a.opportunityId === opportunityId && a.status === "approved"
  ) && opportunities.find((o) => o.id === opportunityId)?.status === "closed";
}
